import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { startServer } from '../../src/runtime/server.js';
import { NodeStorage } from '../../src/storage/node.js';
import { produce, call, req, skill } from '../fixtures/workflow.js';

test('主方案只显示已确认，复制按视图范围，失败可手动复制，窄屏不溢出',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'icon-handoff-'));t.after(()=>rm(directory,{recursive:true,force:true}));
 const storage=await NodeStorage.open(directory);
 const {studio,p,s,i,target}=await produce(storage);
 const {scheme:other}=await call(studio,'create_scheme',{...p,name:'B 备选',requestId:req()});
 const server=await startServer({storage,skill,appDirectory:resolve(process.env.ICON_STUDIO_TEST_APP ?? 'dist/app'),requireUI:true});t.after(()=>server.close());
 const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());
 const page=await browser.newPage({viewport:{width:1400,height:900}});
 await page.addInitScript(()=>{window.copied='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text;},write:async items=>{window.copied=await(await items[0].getType('text/plain')).text();}}});});
 await page.goto(server.url);
 await page.getByRole('button',{name:'连接已有目录',exact:true}).click();
 await expect(page.getByRole('heading',{name:'项目库',exact:true})).toBeVisible();
 await page.goto(`${server.url}/#${encodeURIComponent(JSON.stringify({view:'icons',...s}))}`);
 await expect(page.getByRole('button',{name:'复制给 Agent',exact:true})).toBeVisible();
 await expect(page.locator('.scheme-confirmed')).toHaveCount(0);
 await page.getByRole('button',{name:'复制给 Agent',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>window.copied)).toContain('未指定主方案');
 assert.match(await page.evaluate(()=>window.copied),new RegExp(directory));
 await call(studio,'set_primary_scheme',{...s,evidenceReference:'合成确认',requestId:req()});
 await expect(page.locator('.scheme-confirmed')).toHaveText('已确认');
 await expect(page.locator(`#navigation [data-id="${other.schemeId}"]`)).toHaveClass(/scheme-secondary/);
 await page.locator(`#navigation [data-id="${other.schemeId}"]`).click();
 await expect(page.locator(`#navigation [data-id="${other.schemeId}"]`)).toHaveAttribute('aria-current','page');
 await page.locator(`#navigation [data-id="${s.schemeId}"]`).click();
 await page.getByRole('button',{name:/收件箱/}).click();
 await expect(page.locator('.frame')).toBeVisible();
 await page.getByRole('button',{name:'复制给 Agent',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>window.copied)).toContain('"scope": "variant"');
 assert.ok((await page.evaluate(()=>window.copied)).includes(target.variantId));
 await page.getByRole('button',{name:'应用场景',exact:true}).click();
 await expect(page.getByRole('button',{name:'应用场景',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'复制给 Agent',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>window.copied)).toContain('"scope": "icon"');
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:{write:async()=>{throw Error('denied');},writeText:async()=>{throw Error('denied');}}});});
 await page.getByRole('button',{name:'复制给 Agent',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'给 Agent 的指令'})).toBeVisible();
 await expect(page.getByRole('textbox',{name:'给 Agent 的指令'})).toHaveValue(/get_icon/);
 await page.goto(`${server.url}/#${encodeURIComponent(JSON.stringify({view:'icons',...s}))}`);
 await mkdir('.impeccable/review',{recursive:true});
 await expect(page.getByRole('heading',{name:'图标列表',exact:true})).toBeVisible();
 await expect(page.locator('#handoff-fallback')).toHaveCount(0);
 await expect(page.locator('.scheme-confirmed')).toBeVisible();
 await page.screenshot({path:'.impeccable/review/primary-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await expect(page.getByRole('button',{name:'复制给 Agent',exact:true})).toBeVisible();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'.impeccable/review/primary-mobile.png',fullPage:true});
 await page.locator('#language').click();
 await expect(page.getByRole('button',{name:'Copy for Agent',exact:true})).toBeVisible();
 await expect(page.locator('.scheme-confirmed')).toHaveText('Confirmed');
});
