import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { mkdtemp, rm, mkdir, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { startServer } from '../../src/runtime/server.js';
import { NodeStorage } from '../../src/storage/node.js';
import { operationCatalog } from '../../src/contracts/operations.js';

for (const native of [false, true]) test(`${native ? '原生 WebMCP' : '本地 HTTP'}：空目录到编译、界面、选区、导出、重开`, async t => {
  const directory = await mkdtemp(join(tmpdir(), 'icon-e2e-')); t.after(() => rm(directory, { recursive: true, force: true }));
  const serverOptions = { storage: await NodeStorage.open(directory), skill: { status: 'loaded', version: '0.1.0-dev.2', evidence: 'isolated-e2e' }, buildId: 'sha256-0000000000000000000000000000000000000000000000000000000012345678', appDirectory: resolve(process.env.ICON_STUDIO_TEST_APP ?? 'dist/app'), requireUI: true };
  let server = await startServer(serverOptions); t.after(() => server.close());
  const browser = await chromium.launch({ channel: 'chrome', headless: true, args: native ? ['--enable-experimental-web-platform-features'] : [] }); t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1903, height: 1320 } }); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  let releaseStartup;
  const startupGate = new Promise(resolve => { releaseStartup = resolve; });
  await page.route('**/bootstrap*', async route => { await startupGate; await route.continue(); });
  await page.goto(server.url);
  try {
    await expect(page.locator('.workspace-body')).toBeHidden({timeout:1000});
    await expect(page.locator('#project-label')).toHaveText('');
    await expect(page.locator('#startup')).toBeVisible();
    await page.screenshot({path:'.impeccable/review/startup-loading.png'});
  } finally { releaseStartup(); }
  await page.getByRole('button', { name: '连接已有目录', exact: true }).waitFor();
  await expect(page.locator('#startup')).toBeHidden();
  if (native) await page.waitForFunction(async () => document.modelContext && (await document.modelContext.getTools()).length === 5);
  const invoke = async (name, input = {}) => {
    const response = native ? null : await fetch(`${server.url}/operation`, { method: 'POST', headers: { Authorization: `Bearer ${server.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name, input }) });
    const gateway = name === 'get_workflow' ? 'get_workflow' : operationCatalog[name].mutates ? 'write' : 'read';
    let result = native ? await page.evaluate(async ({name,input,gateway}) => { const tools = await document.modelContext.getTools(); const tool = tools.find(t=>t.name==='icon_studio_v3_'+gateway); const payload=gateway==='get_workflow'?{}:{name,input}; return JSON.parse(await document.modelContext.executeTool(tool,JSON.stringify(payload))); }, {name,input,gateway}) : await response.json();
    while (result.status === 'accepted') { await new Promise(r => setTimeout(r, 30)); result = (await invoke('get_operation', { operationId: result.operationId })).result; }
    assert.equal(result.ok, true, `${name}: ${JSON.stringify(result)}`); return result.data;
  };
  const requestId = () => crypto.randomUUID();
  const checkContentRail = async (limit) => {
    await expect(page.locator('.page-body')).toHaveAttribute('data-layout', limit === 760 ? 'reading' : limit === 1000 ? 'detail' : 'collection');
    await expect.poll(() => page.locator('.page-body').evaluate((el, limit) => {
      const rail = el.getBoundingClientRect(), area = el.closest('#main').getBoundingClientRect();
      return rail.width <= limit && Math.abs(rail.x + rail.width / 2 - area.x - area.width / 2) < 2;
    }, limit), { message: '当前页面内容限宽并在可用主区域居中' }).toBe(true);
  };
  await invoke('connect_library', { create: true, requestId: requestId() });
  await expect(page.locator('#main h1')).toHaveText('项目库');
  await expect(page.locator('#project-label')).toBeHidden();
  await expect(page.locator('#navigation')).toBeHidden();
  await expect(page.locator('.sidebar').getByRole('button', { name: '项目库', exact: true })).toHaveCount(0);
  await expect(page.locator('#language')).toBeVisible();
  await expect(page.locator('.skill-footer')).toBeVisible();
  assert.equal((await page.locator('.content').boundingBox()).x, 0, '项目库内容区不为侧栏预留一列');
  await expect(page.locator('.skill-footer #language')).toBeVisible();
  await expect(page.locator('.workspace-header')).toBeHidden();
  const languageBox = await page.locator('#language').boundingBox();
  const brandBox = await page.locator('.skill-identity').boundingBox();
  assert.ok(Math.abs(languageBox.y + languageBox.height / 2 - brandBox.y - brandBox.height / 2) < 2, '语言切换紧邻品牌并垂直对齐');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'.impeccable/review/library-layout-mobile.png',fullPage:true});
  await page.setViewportSize({width:1903,height:1320});
  const { project } = await invoke('create_project', { requestId: requestId(), name: '合成笔记系统', purpose: '整理条目与项目' }); const p = { projectId: project.projectId };
  const fields = Object.fromEntries(['purpose','stylePreferences','audience','usage','scope','constraints'].map(key => [key, { value: '合成测试：'+key, provenance: { kind: 'user', reference: null, awaitingConfirmation: false } }]));
  await invoke('update_brief', { ...p, requestId: requestId(), content: { fields, vocabularyDraft: [] } });
  await invoke('navigate', { ...p, view: 'project', requestId: requestId() });
  await page.reload();
  await expect(page.locator('#navigation')).toBeHidden();
  await expect(page.locator('.workspace-header .skill-mark')).toHaveCount(0);
  await expect(page.locator('.workspace-header #project-label')).toHaveText('合成笔记系统');
  await expect(page.locator('#project-label')).toBeVisible();
  assert.equal((await page.locator('.content').boundingBox()).x, 224, '进入项目恢复侧栏');
  await page.locator('#library-back').click();
  await expect(page.locator('.sidebar')).toBeHidden();
  assert.equal((await page.locator('.content').boundingBox()).x,0,'返回项目库再次释放侧栏宽度');
  const card = await page.locator('.project-row').boundingBox();
  assert.ok(card.width <= 360, '项目卡片不随宽屏拉长');
  const container = await page.locator('.page-body').boundingBox();
  const libraryMain = await page.locator('#main').boundingBox();
  assert.ok(Math.abs(container.x + container.width / 2 - libraryMain.x - libraryMain.width / 2) < 2, '列表容器居中');
  assert.equal((await page.locator('.project-storage').boundingBox()).x, container.x, '存储信息与列表左对齐');
  await invoke('create_project', {requestId:requestId(), name:'另一个合成项目', purpose:'验证多项目网格'});
  await page.reload();
  await expect(page.locator('.project-row')).toHaveCount(2);
  const diskEntries = await readdir(directory);
  assert.equal(diskEntries.filter(name => name.startsWith('p-')).length, 2);
  assert.equal(diskEntries.includes('projects'), false, '各项目直接保存到共用根目录');
  const storageBeforeSwitch = await invoke('get_storage');
  await page.getByRole('button', { name: /另一个合成项目/ }).click();
  await expect(page.locator('#project-label')).toHaveText('另一个合成项目');
  await page.locator('#library-back').click();
  await expect(page.locator('.project-row')).toHaveCount(2);
  assert.equal((await invoke('get_storage')).location, storageBeforeSwitch.location);
  const cards = await page.locator('.project-row').evaluateAll(items => items.map(item => {const r=item.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width};}));
  assert.equal(cards[0].y,cards[1].y,'宽屏项目卡片并排');
  assert.ok(cards[1].x>cards[0].x && cards.every(card=>card.width<=360));
  await page.screenshot({path:'.impeccable/review/global-library-wide.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'.impeccable/review/global-library-narrow.png',fullPage:true});
  await page.setViewportSize({width:1903,height:1320});
  await page.getByRole('button',{name:/合成笔记系统/}).click();
  await checkContentRail(760);
  await expect(page.locator('.sidebar')).toBeVisible();
  await expect(page.locator('.skill-footer .skill-mark')).toBeVisible();
  await expect(page.locator('.skill-footer')).toContainText('Inspired by');
  await expect(page.locator('.skill-footer a')).toHaveAttribute('href', 'https://www.minoradventures.co/blog/the-making-of-cursors-icons');
  const footerBox = await page.locator('.skill-footer').boundingBox();
  assert.ok(Math.abs(footerBox.y + footerBox.height - 1320) < 2, '品牌与文章来源固定在侧栏底部');
  await expect(page.getByRole('button', { name: '返回项目库', exact: true })).toBeVisible();
  await expect(page.locator('.workflow-steps [aria-current="step"]')).toHaveText(/确认需求/);
  await expect(page.locator('.brief-instruction')).toHaveText('请在输入框中确认需求信息是否正确。如果不正确，请直接对话进行修改。如果需求信息没问题，请回复“需求已确认”。');
  if (!native) { await mkdir('.impeccable/review', { recursive: true }); await page.screenshot({ path: '.impeccable/review/brief-confirmation-desktop.png', fullPage: true }); }
  await expect(page.getByRole('heading', { name: '风格偏好', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '目标', exact: true })).toHaveCount(0);
  await expect(page.locator('.workflow-progress')).not.toContainText('步骤');
  assert.equal(await page.locator('.brief section').evaluateAll(sections => sections.every(section => {
    const heading = section.querySelector('h2').getBoundingClientRect();
    const body = section.querySelector('p').getBoundingClientRect();
    return body.top >= heading.bottom && Math.abs(body.left - heading.left) < 1;
  })), true, '每个字段名独占一行，内容在其下方左对齐');
  assert.equal(await page.locator('#main input, #main textarea, #main [contenteditable=true]').count(), 0);
  assert.equal(await page.locator('.workflow-steps button').count(), 0);
  await expect.poll(() => page.locator('.brief-onboarding').evaluate(el => {
    const briefBox = el.getBoundingClientRect(), bodyBox = el.closest('#main').getBoundingClientRect();
    return Math.abs(briefBox.x + briefBox.width / 2 - (bodyBox.x + bodyBox.width / 2));
  }), { message: '需求内容栏在扣除滚动条预留空间后的页面居中' }).toBeLessThan(2);
  await page.setViewportSize({ width: 390, height: 844 });
  if (!native) await page.screenshot({ path: '.impeccable/review/brief-confirmation-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.locator('.workflow-steps [aria-current="step"]')).toHaveText(/Confirm brief/);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name: '中文', exact: true }).click();
  await page.setViewportSize({ width: 1903, height: 1320 });
  let { confirmation } = await invoke('prepare_confirmation', p);
  await invoke('confirm_brief', { ...p, requestId: requestId(), confirmationId: confirmation.confirmationId, evidenceReference: '测试确认' });
  await expect(page.locator('.workflow-steps [aria-current="step"]')).toHaveText(/生成方案/);
  await expect(page.locator('#navigation')).toBeHidden();
  const { scheme } = await invoke('create_scheme', { ...p, requestId: requestId(), name: '基础方案' }); const s = { ...p, schemeId: scheme.schemeId };
  await expect(page.locator('#navigation')).toBeVisible();
  await expect(page.locator('#navigation').getByRole('button', { name: '基础方案', exact: true })).toBeVisible();
  await expect(page.locator('.brief-onboarding')).toHaveCount(0);
  for (const name of ['C · 三','B · 二','A · 一']) await invoke('create_scheme', { ...p, name, requestId: requestId() });
  await expect(page.locator('#navigation button').filter({hasText:/^[ABC] · /})).toHaveText(['A · 一','B · 二','C · 三']);
  assert.equal(await page.locator('.sidebar .skill-footer #language').count(), 1);
  assert.equal((await page.locator('.content').boundingBox()).y, 0, '主内容从页面顶部开始');
  await expect(page.locator('.workspace-header').getByRole('button', { name: '返回项目库', exact: true })).toBeVisible();
  await expect(page.locator('#project-info').getByRole('button', { name: '项目信息', exact: true })).toBeVisible();
  await expect(page.locator('.sidebar details')).toHaveCount(0);
  await expect(page.locator('.workspace-header #library-back svg')).toHaveCount(1);
  await expect(page.locator('#main #storage-location')).toBeVisible();
  await expect(page.locator('#storage-location')).toHaveText(serverOptions.storage.identity);
  await expect(page.locator('.project-storage small')).toContainText('0.1.0-dev.2');
  await expect(page.locator('.project-storage small')).toContainText('12345678');
  assert.equal((await invoke('get_storage')).location, serverOptions.storage.identity);
  await page.getByRole('button', { name: '刷新', exact: true }).click();
  await expect(page.locator('#main #storage-location')).toHaveText(serverOptions.storage.identity);
  assert.equal(await page.locator('.nav-footer').count(), 0);
  await expect(page.locator('#inspector')).toBeHidden();
  await invoke('set_design_rules', { ...s, requestId: requestId(), content: { gridSize: 16, padding: 1, strokeWidth: 1.25, cornerRadius: 1, lineCap: 'round', lineJoin: 'round', opticalNotes: [] } });
  const { icons } = await invoke('register_icons', { ...p, requestId: requestId(), icons: [{ name: '收件箱', concept: '集中接收的条目', tags: ['收件','inbox'], usages: [] }] }); const i = { ...s, iconId: icons[0].iconId };
  const { variants } = await invoke('register_variants', { ...i, requestId: requestId(), variants: [{ size: 16, style: 'outline', weight: 'regular' }] }); const v = { ...i, variantId: variants[0].variantId };
  const { batch } = await invoke('create_batch', { ...s, requestId: requestId(), targets: [{ iconId: v.iconId, variantId: v.variantId }] });
  await invoke('start_batch', { ...p, batchId: batch.batchId, requestId: requestId() });
  await invoke('apply_operations', { ...v, taskId: batch.taskIds[0], requestId: requestId(), operations: [{ op: 'add_layer', layer: { layerId: 'l-shell', name: '外壳', type: 'path', visible: true, drawing: 'stroke', strokeWidth: 1.25, closed: true,
    nodes: [[3,4],[13,4],[13,12],[3,12]].map((point,n) => ({ nodeId: 'n-'+n, point, in: null, out: null })) } }] });
  assert.equal((await invoke('compile_scheme',{ ...s,requestId:requestId() })).items[0].ok,true);
  const { batch: inspectionBatch } = await invoke('create_batch', { ...s, requestId: requestId(), targets: [{ iconId: v.iconId, variantId: v.variantId }] });
  await invoke('start_batch', { ...p, batchId: inspectionBatch.batchId, requestId: requestId() });
  await invoke('apply_operations', { ...v, taskId: inspectionBatch.taskIds[0], requestId: requestId(), operations: [{op:'add_layer', layer:{layerId:'l-ring',name:'组合',type:'boolean',visible:true,operation:'subtract',children:[
    {layerId:'l-outer',name:'外框',type:'rect',visible:true,drawing:'fill',strokeWidth:0,radius:1,x:5,y:6,width:6,height:4},
    {layerId:'l-inner',name:'内空',type:'rect',visible:true,drawing:'fill',strokeWidth:0,radius:0,x:6,y:7,width:4,height:2},
  ]}}] });
  assert.equal((await invoke('compile_scheme',{ ...s,requestId:requestId() })).items[0].ok,true);
  await invoke('set_usage_bindings',{ ...v,requestId:requestId(),bindings:['toolbar'] });
  await invoke('navigate',{ ...s,view:'icons',requestId:requestId() });
  await page.goto(server.url); await page.getByRole('heading',{name:'图标列表',exact:true}).waitFor();
  await checkContentRail(1120);
  await page.getByRole('combobox',{name:'标签',exact:true}).selectOption('inbox');
  await expect(page.locator('#tags')).toHaveValue('inbox');
  await expect.poll(async()=> (await invoke('get_view_context')).options.tag).toBe('inbox');
  if(!native)await page.screenshot({path:'.impeccable/review/select-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  if(!native)await page.screenshot({path:'.impeccable/review/select-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('combobox',{name:'标签',exact:true}).selectOption('');
  await expect.poll(async()=> (await invoke('get_view_context')).options.tag).toBe(null);
  await page.setViewportSize({width:1903,height:1320});
  await page.getByRole('button',{name:/收件箱/}).click(); await page.getByRole('button',{name:'下载 SVG',exact:true}).waitFor();
  await checkContentRail(1000);
  const { variants: larger } = await invoke('register_variants', {...i,requestId:requestId(),variants:[{size:64,style:'outline',weight:'regular'}]});
  const largeTarget={...i,variantId:larger[0].variantId};
  const {batch:largeBatch}=await invoke('create_batch',{...s,requestId:requestId(),targets:[{iconId:i.iconId,variantId:largeTarget.variantId}]});
  await invoke('start_batch',{...p,batchId:largeBatch.batchId,requestId:requestId()});
  await invoke('apply_operations',{...largeTarget,taskId:largeBatch.taskIds[0],requestId:requestId(),operations:[{op:'add_layer',layer:{layerId:'l-large',name:'大图标',type:'rect',visible:true,drawing:'stroke',strokeWidth:2,radius:4,x:12,y:12,width:40,height:40}}]});
  await expect(page.getByRole('button',{name:'64 × 64 px · 描边 · 常规',exact:true})).toBeVisible();
  const heading=await page.locator('.title h1').boundingBox(),switchBox=await page.locator('.preview-switch').boundingBox();
  assert.ok(switchBox.x>heading.x+heading.width && Math.abs(switchBox.y-heading.y)<10,'模式切换在标题右侧');
  const frameBefore=await page.locator('.frame').boundingBox();
  await page.getByRole('button',{name:'64 × 64 px · 描边 · 常规',exact:true}).click();
  await expect(page.locator('#inspector')).toContainText('64 × 64 px');
  const frameAfter=await page.locator('.frame').boundingBox();
  assert.ok(Math.abs(frameBefore.width-frameAfter.width)<1 && Math.abs(frameBefore.height-frameAfter.height)<1,'尺寸切换不改变预览框宽高');
  await page.getByRole('button',{name:'16 × 16 px · 描边 · 常规',exact:true}).click();
  await expect(page.locator('#inspector')).toContainText('16 × 16 px');
  await page.getByRole('button',{name:'内空',exact:true}).click();
  await expect(page.locator('.geometry-selection')).toBeVisible();
  await expect(page.locator('.geometry-selection')).toHaveAttribute('data-layer-id','l-inner');
  await expect(page.locator('.properties')).toContainText('宽度');
  await expect(page.getByRole('button',{name:'内空',exact:true})).toBeFocused();
  assert.deepEqual((await invoke('get_layer',{...v,layerId:'l-inner'})).preview.bounds,{left:6,top:7,right:10,bottom:9});
  assert.equal(await page.locator('.selection-node').count(),0,'矩形不伪装成路径节点');
  const indent=await page.getByRole('button',{name:'内空',exact:true}).evaluate(el=>parseFloat(getComputedStyle(el).paddingLeft));
  assert.ok(indent>await page.getByRole('button',{name:'组合',exact:true}).evaluate(el=>parseFloat(getComputedStyle(el).paddingLeft)));
  await page.getByRole('button',{name:'内空',exact:true}).click();
  await expect(page.locator('.geometry-selection')).toHaveCount(0);
  await expect(page.locator('#inspector')).toContainText('选择图层查看属性。');
  assert.equal((await invoke('get_selection')).selection.layerId,null,'再次点击已选图层取消选择');
  await expect(page.getByRole('button',{name:'内空',exact:true})).toBeFocused();
  await page.getByRole('button',{name:'组合',exact:true}).click();
  await expect(page.locator('.geometry-selection')).toHaveAttribute('data-layer-id','l-ring');
  const actualCenter=await page.locator('.actual').evaluate(el=>{const items=[...el.children],first=items[0].getBoundingClientRect(),last=items.at(-1).getBoundingClientRect(),box=el.getBoundingClientRect();return Math.abs((first.left+last.right)/2-(box.left+box.right)/2);});
  assert.ok(actualCenter<2,'实际尺寸对比居中');
  if(!native) await page.screenshot({path:'.impeccable/review/layer-selection-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.locator('.canvas svg').evaluate(el=>el.getBoundingClientRect().width)).toBeLessThan(350);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  if(!native) await page.screenshot({path:'.impeccable/review/layer-selection-mobile.png',fullPage:true});
  await page.setViewportSize({width:1903,height:1320});
  await expect.poll(()=>page.locator('.canvas svg').evaluate(el=>el.getBoundingClientRect().width)).toBe(520);
  await page.getByRole('button',{name:'外壳',exact:true}).click();
  await expect(page.locator('.geometry-selection')).toHaveAttribute('data-layer-id','l-shell');
  await expect(page.locator('#nodes')).toHaveCount(0);
  await expect(page.locator('.selection-node')).toHaveCount(0);
  let selected=await invoke('get_selection');assert.equal(selected.selection.layerId,'l-shell');
  await mkdir('.impeccable/review',{recursive:true});if(!native)await page.screenshot({path:'.impeccable/review/user-1903.png',fullPage:true});
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载 SVG',exact:true}).click();assert.match((await download).suggestedFilename(),/\.svg$/);
  await page.getByRole('button',{name:'应用场景',exact:true}).click();await page.locator('.scene-sample').first().waitFor();
  await checkContentRail(1000);
  assert.ok(await page.locator('.scene-section').first().evaluate(el=>{const box=el.getBoundingClientRect(),main=document.querySelector('main').getBoundingClientRect();return Math.abs((box.left+box.right-main.left-main.right)/2)<2;}),'场景内容栏在主内容区居中');
  selected=await invoke('get_selection');assert.equal(selected.selection.variantId,null);assert.equal(selected.selection.nodeId,null);
  if(!native)await page.screenshot({path:'.impeccable/review/desktop-scenes.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});if(!native)await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.reload();await page.locator('.scene-sample').first().waitFor();
  await page.getByRole('button',{name:'EN',exact:true}).click();
  await page.getByRole('button',{name:'Structure',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('button',{name:'中文',exact:true}).click();
  // Feedback, paused work and confirmed content survive a real server restart, not just reload.
  const originalPreview=await invoke('preview_icon',v);
  await invoke('record_review',{...v,contentHash:originalPreview.contentHash,status:'accepted',comment:null,evidenceReference:'合成用户确认',requestId:requestId()});
  const {feedback}=await invoke('record_feedback',{...v,comment:'左上节点向右移动一个单位',requestId:requestId()});
  const {batch:followup}=await invoke('create_batch',{...s,targets:[{iconId:v.iconId,variantId:v.variantId}],requestId:requestId()});
  await invoke('start_batch',{...p,batchId:followup.batchId,requestId:requestId()});
  await invoke('pause_task',{...p,taskId:followup.taskIds[0],requestId:requestId()});
  await server.close();server=await startServer(serverOptions);await page.goto(server.url);
  await page.getByRole('button',{name:'连接已有目录',exact:true}).waitFor();
  if(native)await page.waitForFunction(async()=>document.modelContext&&(await document.modelContext.getTools()).length===5);
  await invoke('connect_library',{create:false,requestId:requestId()});
  assert.ok((await invoke('list_projects',{})).items.some(item=>item.projectId===p.projectId));
  assert.ok((await invoke('get_recovery',p)).tasks.some(task=>task.taskId===followup.taskIds[0]&&task.status==='paused'));
  await invoke('resume_task',{...p,taskId:followup.taskIds[0],requestId:requestId()});
  await invoke('apply_operations',{...v,taskId:followup.taskIds[0],operations:[{op:'move_node',layerId:'l-shell',nodeId:'n-0',handle:'point',point:[4,4]}],requestId:requestId()});
  assert.equal((await invoke('get_review_status',v)).status,'stale');
  assert.ok((await invoke('compile_scheme',{...s,requestId:requestId()})).items.every(item=>item.ok));
  await invoke('resolve_feedback',{...p,feedbackId:feedback.feedbackId,requestId:requestId()});
  const {delivery}=await invoke('prepare_export',{...v,scope:'variant',kind:'svg',requestId:requestId()});
  assert.ok((await invoke('read_artifact',{...p,exportId:delivery.exportId,artifactId:delivery.artifacts[0].artifactId})).content.includes('<path'));
  if (!native) {
    await page.setViewportSize({ width: 1903, height: 1320 });
    await page.getByRole('button', { name: '断开目录', exact: true }).click();
    await expect(page.getByRole('button', { name: '连接已有目录', exact: true })).toBeVisible();
    assert.equal((await invoke('get_storage')).location, null);
    await page.getByRole('button', { name: '连接已有目录', exact: true }).click();
    await expect(page.locator('#storage-location')).toBeVisible();
    const beforeError = await page.locator('.workspace-body').boundingBox();
    await page.route('**/operation', route => route.abort('failed'));
    await page.locator('#language').click();
    await expect(page.locator('#error')).toBeVisible();
    const afterError = await page.locator('.workspace-body').boundingBox();
    assert.deepEqual(afterError, beforeError, '错误提示不能移动或改变页面内容尺寸');
    await page.screenshot({ path: '.impeccable/review/error-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    const alertBox = await page.locator('#error').boundingBox();
    assert.ok(alertBox.x >= 0 && alertBox.x + alertBox.width <= 390);
    await page.screenshot({ path: '.impeccable/review/error-mobile.png', fullPage: true });
  }
  assert.deepEqual(errors,[]);
  console.log('Native WebMCP available:',await page.evaluate(()=>Boolean(document.modelContext?.registerTool)));
});
