import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, appendFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { prepareRelease, readRelease } from '../../scripts/release-skill.js';

test('同一候选包含可校验的 GitHub 下载清单，重复运行不覆盖，损坏包被拒绝', async t => {
  const root = await mkdtemp(join(tmpdir(), 'boplet-release-test-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const directory = join(root, 'candidate');
  const { version } = JSON.parse(await readFile('package.json', 'utf8'));
  const report = await prepareRelease(directory, { tag: `v${version}` });
  const manifest = await readRelease(directory);
  assert.equal(report.published, false);
  assert.equal(manifest.version, version);
  assert.equal(manifest.repository, 'walnut-a/boplet-icon-studio');
  assert.equal(manifest.url, `https://github.com/walnut-a/boplet-icon-studio/releases/download/v${version}/make-product-icons-${version}.zip`);
  const bytes = await readFile(join(directory, manifest.filename));
  assert.equal(createHash('sha256').update(bytes).digest('hex'), manifest.sha256);
  const web = join(root, 'web');
  execFileSync(process.execPath, ['scripts/release-web.js', '--skill-release', directory, '--output', web]);
  assert.deepEqual(JSON.parse(await readFile(join(web, 'downloads/release.json'), 'utf8')), manifest);
  assert.equal(await readFile(join(web, 'skill/SKILL.md'), 'utf8'), await readFile(join(directory, 'skill/SKILL.md'), 'utf8'));
  const legacy = { ...manifest, repository: 'walnut-a/icon-studio', url: manifest.url.replace('walnut-a/boplet-icon-studio/', 'walnut-a/icon-studio/') };
  await writeFile(join(directory, 'release.json'), JSON.stringify(legacy));
  assert.deepEqual(await readRelease(directory), legacy, '改名前的不可变发布清单仍可校验');
  execFileSync(process.execPath, ['scripts/release-web.js', '--skill-release', directory, '--output', join(root, 'legacy-web')]);
  assert.deepEqual(JSON.parse(await readFile(join(root, 'legacy-web/downloads/release.json'), 'utf8')), manifest, '官网索引使用新仓库地址，版本与包校验值保持一致');
  assert.deepEqual(JSON.parse(await readFile(join(directory, 'release.json'), 'utf8')), legacy, '不修改原发布候选');
  await writeFile(join(directory, 'release.json'), JSON.stringify({ ...legacy, url: manifest.url }));
  await assert.rejects(readRelease(directory), /校验/, '仓库与下载地址必须一致');
  await writeFile(join(directory, 'release.json'), JSON.stringify({ ...legacy, repository: 'other/repository', url: legacy.url.replace('walnut-a/icon-studio/', 'other/repository/') }));
  await assert.rejects(readRelease(directory), /校验/, '不能接受未授权的仓库');
  await writeFile(join(directory, 'release.json'), JSON.stringify(legacy));
  await assert.rejects(prepareRelease(directory, { tag: `v${version}` }), /非空/);
  await assert.rejects(prepareRelease(join(root, 'wrong-tag'), { tag: 'v9.0.0' }), /版本/);
  await appendFile(join(directory, manifest.filename), 'tamper');
  await assert.rejects(readRelease(directory), /校验/);
});
